name: cd

on:
    push:
        branches: [main]

jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-latest
        timeout-minutes: 10

        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Set up Go
              uses: actions/setup-go@v5
              with:
                go-version: "1.23.0"

            - name: Set up Goose
              run: go install github.com/pressly/goose/v3/cmd/goose@latest

            - name: Build app
              run: ./scripts/buildprod.sh

            - name: Run migrations
              run: ./scripts/migrateup.sh

            - id: auth
              uses: google-github-actions/auth@v2
              with:
                credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

            - name: Set up Cloud SDK
              uses: google-github-actions/setup-gcloud@v2
          
            - name: Use gcloud CLI
              run: gcloud info

            - name: Build and push Docker image
              run: gcloud builds submit --tag europe-southwest1-docker.pkg.dev/notely-451123/notely-ar-repo/notely:latest .

            - name: Deploy to Cloud Run
              run: gcloud run deploy notely --image europe-southwest1-docker.pkg.dev/notely-451123/notely-ar-repo/notely:latest --region europe-southwest1 --allow-unauthenticated --project notely-451123 --max-instances=4

            
        



        